// Comprehensive emoji dataset organized by category with search keywords.
// Each emoji has: emoji character, short name, and search keywords.

export interface EmojiItem {
  emoji: string
  name: string
  keywords: string[]
}

export interface EmojiCategory {
  id: string
  icon: string
  emojis: EmojiItem[]
}

// Skin tone modifiers
export const SKIN_TONES = [
  { id: 'default', label: 'Default', modifier: '' },
  { id: 'light', label: 'Light', modifier: '\u{1F3FB}' },
  { id: 'medium-light', label: 'Medium Light', modifier: '\u{1F3FC}' },
  { id: 'medium', label: 'Medium', modifier: '\u{1F3FD}' },
  { id: 'medium-dark', label: 'Medium Dark', modifier: '\u{1F3FE}' },
  { id: 'dark', label: 'Dark', modifier: '\u{1F3FF}' },
] as const

export type SkinToneId = typeof SKIN_TONES[number]['id']

// Emojis that support skin tone modifiers
const SKIN_TONE_BASE = new Set([
  '👋', '🤚', '🖐️', '✋', '🖖', '🫱', '🫲', '🫳', '🫴', '👌', '🤌', '🤏',
  '✌️', '🤞', '🫰', '🤟', '🤘', '🤙', '👈', '👉', '👆', '🖕', '👇', '☝️',
  '🫵', '👍', '👎', '✊', '👊', '🤛', '🤜', '👏', '🙌', '🫶', '👐', '🤲',
  '🤝', '🙏', '✍️', '💅', '🤳', '💪', '🦵', '🦶', '👂', '🦻', '👃',
  '👶', '🧒', '👦', '👧', '🧑', '👱', '👨', '🧔', '👩', '🧓', '👴', '👵',
  '🙍', '🙎', '🙅', '🙆', '💁', '🙋', '🧏', '🙇', '🤦', '🤷',
  '👮', '🕵️', '💂', '🥷', '👷', '🫅', '🤴', '👸', '👳', '👲',
  '🧕', '🤵', '👰', '🤰', '🫃', '🫄', '🤱', '👼', '🎅', '🤶',
  '🦸', '🦹', '🧙', '🧚', '🧛', '🧜', '🧝', '🧞', '🧟',
  '💆', '💇', '🚶', '🧍', '🧎', '🏃', '💃', '🕺', '🕴️',
  '👯', '🧖', '🧗', '🤸', '⛹️', '🏋️', '🚴', '🚵', '🤽',
  '🤾', '🤺', '⛷️', '🏂', '🏌️', '🏇', '🏊', '🤼', '🤹',
  '🧘', '🛀', '🛌', '👭', '👫', '👬',
])

export function supportsSkintone(emoji: string): boolean {
  return SKIN_TONE_BASE.has(emoji)
}

export function applySkintone(emoji: string, skinToneId: SkinToneId): string {
  if (skinToneId === 'default' || !supportsSkintone(emoji)) return emoji
  const modifier = SKIN_TONES.find(s => s.id === skinToneId)?.modifier ?? ''
  if (!modifier) return emoji
  // Remove any existing skin tone modifier first
  const base = emoji.replace(/[\u{1F3FB}-\u{1F3FF}]/u, '')
  // Insert modifier after the first code point
  const chars = [...base]
  if (chars.length === 0) return emoji
  return chars[0] + modifier + chars.slice(1).join('')
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: 'smileys',
    icon: '😀',
    emojis: [
      { emoji: '😀', name: 'grinning', keywords: ['happy', 'smile', 'grin'] },
      { emoji: '😃', name: 'smiley', keywords: ['happy', 'smile'] },
      { emoji: '😄', name: 'smile', keywords: ['happy', 'joy'] },
      { emoji: '😁', name: 'grin', keywords: ['happy'] },
      { emoji: '😆', name: 'laughing', keywords: ['happy', 'laugh'] },
      { emoji: '😅', name: 'sweat_smile', keywords: ['nervous', 'laugh'] },
      { emoji: '🤣', name: 'rofl', keywords: ['laugh', 'funny', 'lol'] },
      { emoji: '😂', name: 'joy', keywords: ['laugh', 'tears', 'funny', 'lol'] },
      { emoji: '🙂', name: 'slightly_smiling', keywords: ['smile'] },
      { emoji: '🙃', name: 'upside_down', keywords: ['sarcasm'] },
      { emoji: '😉', name: 'wink', keywords: ['flirt'] },
      { emoji: '😊', name: 'blush', keywords: ['happy', 'shy'] },
      { emoji: '😇', name: 'innocent', keywords: ['angel', 'halo'] },
      { emoji: '🥰', name: 'smiling_hearts', keywords: ['love', 'adore'] },
      { emoji: '😍', name: 'heart_eyes', keywords: ['love', 'crush'] },
      { emoji: '🤩', name: 'star_struck', keywords: ['wow', 'excited'] },
      { emoji: '😘', name: 'kissing_heart', keywords: ['love', 'kiss'] },
      { emoji: '😗', name: 'kissing', keywords: ['kiss'] },
      { emoji: '😚', name: 'kissing_closed_eyes', keywords: ['kiss'] },
      { emoji: '😙', name: 'kissing_smiling_eyes', keywords: ['kiss'] },
      { emoji: '🥲', name: 'smiling_tear', keywords: ['sad', 'happy'] },
      { emoji: '😋', name: 'yum', keywords: ['delicious', 'food'] },
      { emoji: '😛', name: 'stuck_out_tongue', keywords: ['playful'] },
      { emoji: '😜', name: 'stuck_out_tongue_wink', keywords: ['playful', 'joke'] },
      { emoji: '🤪', name: 'zany', keywords: ['crazy', 'wild'] },
      { emoji: '😝', name: 'stuck_out_tongue_closed_eyes', keywords: ['playful'] },
      { emoji: '🤑', name: 'money_mouth', keywords: ['rich', 'money'] },
      { emoji: '🤗', name: 'hugging', keywords: ['hug', 'love'] },
      { emoji: '🤭', name: 'hand_over_mouth', keywords: ['oops', 'giggle'] },
      { emoji: '🫢', name: 'hand_mouth_open', keywords: ['surprised', 'oops'] },
      { emoji: '🫣', name: 'peeking', keywords: ['shy', 'nervous'] },
      { emoji: '🤫', name: 'shushing', keywords: ['quiet', 'secret'] },
      { emoji: '🤔', name: 'thinking', keywords: ['hmm', 'wonder'] },
      { emoji: '🫡', name: 'saluting', keywords: ['salute', 'respect'] },
      { emoji: '🤐', name: 'zipper_mouth', keywords: ['secret', 'quiet'] },
      { emoji: '🤨', name: 'raised_eyebrow', keywords: ['skeptical', 'doubt'] },
      { emoji: '😐', name: 'neutral', keywords: ['meh', 'blank'] },
      { emoji: '😑', name: 'expressionless', keywords: ['blank'] },
      { emoji: '😶', name: 'no_mouth', keywords: ['silent', 'speechless'] },
      { emoji: '🫥', name: 'dotted_line_face', keywords: ['invisible', 'hidden'] },
      { emoji: '😏', name: 'smirk', keywords: ['flirt', 'suggestive'] },
      { emoji: '😒', name: 'unamused', keywords: ['annoyed', 'bored'] },
      { emoji: '🙄', name: 'eye_roll', keywords: ['annoyed', 'whatever'] },
      { emoji: '😬', name: 'grimacing', keywords: ['awkward', 'nervous'] },
      { emoji: '🫠', name: 'melting', keywords: ['hot', 'embarrassed'] },
      { emoji: '😮‍💨', name: 'exhaling', keywords: ['relief', 'sigh'] },
      { emoji: '🤥', name: 'lying', keywords: ['lie', 'pinocchio'] },
      { emoji: '😌', name: 'relieved', keywords: ['calm', 'peaceful'] },
      { emoji: '😔', name: 'pensive', keywords: ['sad', 'thoughtful'] },
      { emoji: '😪', name: 'sleepy', keywords: ['tired'] },
      { emoji: '🤤', name: 'drooling', keywords: ['hungry', 'want'] },
      { emoji: '😴', name: 'sleeping', keywords: ['zzz', 'tired'] },
      { emoji: '😷', name: 'mask', keywords: ['sick', 'covid'] },
      { emoji: '🤒', name: 'thermometer', keywords: ['sick', 'fever'] },
      { emoji: '🤕', name: 'bandage', keywords: ['hurt', 'injured'] },
      { emoji: '🤢', name: 'nauseated', keywords: ['sick', 'gross'] },
      { emoji: '🤮', name: 'vomiting', keywords: ['sick', 'gross'] },
      { emoji: '🥵', name: 'hot_face', keywords: ['hot', 'heat'] },
      { emoji: '🥶', name: 'cold_face', keywords: ['cold', 'frozen'] },
      { emoji: '🥴', name: 'woozy', keywords: ['drunk', 'dizzy'] },
      { emoji: '😵', name: 'dizzy_face', keywords: ['dizzy', 'confused'] },
      { emoji: '😵‍💫', name: 'spiral_eyes', keywords: ['dizzy', 'hypnotized'] },
      { emoji: '🤯', name: 'exploding_head', keywords: ['mind_blown', 'shocked'] },
      { emoji: '🤠', name: 'cowboy', keywords: ['cowboy', 'western'] },
      { emoji: '🥳', name: 'partying', keywords: ['party', 'celebrate'] },
      { emoji: '🥸', name: 'disguised', keywords: ['disguise'] },
      { emoji: '😎', name: 'sunglasses', keywords: ['cool', 'chill'] },
      { emoji: '🤓', name: 'nerd', keywords: ['nerd', 'geek'] },
      { emoji: '🧐', name: 'monocle', keywords: ['inspect', 'curious'] },
      { emoji: '😕', name: 'confused', keywords: ['puzzled'] },
      { emoji: '🫤', name: 'diagonal_mouth', keywords: ['unsure', 'skeptical'] },
      { emoji: '😟', name: 'worried', keywords: ['concerned'] },
      { emoji: '🙁', name: 'slightly_frowning', keywords: ['sad'] },
      { emoji: '☹️', name: 'frowning', keywords: ['sad'] },
      { emoji: '😮', name: 'open_mouth', keywords: ['surprised', 'wow'] },
      { emoji: '😯', name: 'hushed', keywords: ['surprised'] },
      { emoji: '😲', name: 'astonished', keywords: ['surprised', 'shocked'] },
      { emoji: '😳', name: 'flushed', keywords: ['embarrassed', 'shy'] },
      { emoji: '🥺', name: 'pleading', keywords: ['puppy_eyes', 'cute', 'please'] },
      { emoji: '🥹', name: 'holding_back_tears', keywords: ['emotional', 'touched'] },
      { emoji: '😦', name: 'frowning_open_mouth', keywords: ['shocked'] },
      { emoji: '😧', name: 'anguished', keywords: ['shocked', 'pain'] },
      { emoji: '😨', name: 'fearful', keywords: ['scared', 'afraid'] },
      { emoji: '😰', name: 'anxious_sweat', keywords: ['nervous'] },
      { emoji: '😥', name: 'sad_relieved', keywords: ['disappointed'] },
      { emoji: '😢', name: 'cry', keywords: ['sad', 'tear'] },
      { emoji: '😭', name: 'sob', keywords: ['sad', 'crying'] },
      { emoji: '😱', name: 'scream', keywords: ['scared', 'horror'] },
      { emoji: '😖', name: 'confounded', keywords: ['frustrated'] },
      { emoji: '😣', name: 'persevere', keywords: ['struggle'] },
      { emoji: '😞', name: 'disappointed', keywords: ['sad'] },
      { emoji: '😓', name: 'downcast_sweat', keywords: ['tired', 'sad'] },
      { emoji: '😩', name: 'weary', keywords: ['tired'] },
      { emoji: '😫', name: 'tired', keywords: ['exhausted'] },
      { emoji: '🥱', name: 'yawning', keywords: ['bored', 'sleepy'] },
      { emoji: '😤', name: 'triumph', keywords: ['angry', 'determined'] },
      { emoji: '😡', name: 'rage', keywords: ['angry', 'mad'] },
      { emoji: '😠', name: 'angry', keywords: ['mad', 'upset'] },
      { emoji: '🤬', name: 'cursing', keywords: ['angry', 'swear'] },
      { emoji: '😈', name: 'smiling_devil', keywords: ['evil', 'mischief'] },
      { emoji: '👿', name: 'angry_devil', keywords: ['evil'] },
      { emoji: '💀', name: 'skull', keywords: ['dead', 'death'] },
      { emoji: '☠️', name: 'skull_crossbones', keywords: ['death', 'danger'] },
      { emoji: '💩', name: 'poop', keywords: ['poo', 'shit'] },
      { emoji: '🤡', name: 'clown', keywords: ['clown', 'funny'] },
      { emoji: '👹', name: 'ogre', keywords: ['monster'] },
      { emoji: '👺', name: 'goblin', keywords: ['monster'] },
      { emoji: '👻', name: 'ghost', keywords: ['halloween', 'spooky'] },
      { emoji: '👽', name: 'alien', keywords: ['ufo', 'extraterrestrial'] },
      { emoji: '👾', name: 'space_invader', keywords: ['game', 'alien'] },
      { emoji: '🤖', name: 'robot', keywords: ['bot', 'machine'] },
      { emoji: '😺', name: 'smiley_cat', keywords: ['cat', 'happy'] },
      { emoji: '😸', name: 'smile_cat', keywords: ['cat'] },
      { emoji: '😹', name: 'joy_cat', keywords: ['cat', 'laugh'] },
      { emoji: '😻', name: 'heart_eyes_cat', keywords: ['cat', 'love'] },
      { emoji: '😼', name: 'smirk_cat', keywords: ['cat'] },
      { emoji: '😽', name: 'kissing_cat', keywords: ['cat'] },
      { emoji: '🙀', name: 'scream_cat', keywords: ['cat', 'scared'] },
      { emoji: '😿', name: 'crying_cat', keywords: ['cat', 'sad'] },
      { emoji: '😾', name: 'pouting_cat', keywords: ['cat', 'angry'] },
    ],
  },
  {
    id: 'people',
    icon: '👋',
    emojis: [
      { emoji: '👋', name: 'wave', keywords: ['hello', 'hi', 'goodbye'] },
      { emoji: '🤚', name: 'raised_back_hand', keywords: ['stop'] },
      { emoji: '🖐️', name: 'hand_splayed', keywords: ['high_five'] },
      { emoji: '✋', name: 'raised_hand', keywords: ['stop', 'high_five'] },
      { emoji: '🖖', name: 'vulcan', keywords: ['spock'] },
      { emoji: '👌', name: 'ok_hand', keywords: ['perfect', 'good'] },
      { emoji: '🤌', name: 'pinched_fingers', keywords: ['italian'] },
      { emoji: '🤏', name: 'pinching_hand', keywords: ['small', 'tiny'] },
      { emoji: '✌️', name: 'peace', keywords: ['victory', 'two'] },
      { emoji: '🤞', name: 'crossed_fingers', keywords: ['luck', 'hope'] },
      { emoji: '🫰', name: 'hand_with_index_finger_and_thumb_crossed', keywords: ['money', 'snap'] },
      { emoji: '🤟', name: 'love_you', keywords: ['love'] },
      { emoji: '🤘', name: 'metal', keywords: ['rock'] },
      { emoji: '🤙', name: 'call_me', keywords: ['phone'] },
      { emoji: '👈', name: 'point_left', keywords: ['left'] },
      { emoji: '👉', name: 'point_right', keywords: ['right'] },
      { emoji: '👆', name: 'point_up', keywords: ['up'] },
      { emoji: '🖕', name: 'middle_finger', keywords: ['rude'] },
      { emoji: '👇', name: 'point_down', keywords: ['down'] },
      { emoji: '☝️', name: 'point_up_2', keywords: ['up'] },
      { emoji: '🫵', name: 'index_pointing_at_viewer', keywords: ['you'] },
      { emoji: '👍', name: 'thumbsup', keywords: ['yes', 'good', 'like', 'approve'] },
      { emoji: '👎', name: 'thumbsdown', keywords: ['no', 'bad', 'dislike'] },
      { emoji: '✊', name: 'fist', keywords: ['power', 'punch'] },
      { emoji: '👊', name: 'punch', keywords: ['hit'] },
      { emoji: '🤛', name: 'fist_left', keywords: ['fistbump'] },
      { emoji: '🤜', name: 'fist_right', keywords: ['fistbump'] },
      { emoji: '👏', name: 'clap', keywords: ['applause', 'bravo'] },
      { emoji: '🙌', name: 'raised_hands', keywords: ['celebrate', 'hooray'] },
      { emoji: '🫶', name: 'heart_hands', keywords: ['love'] },
      { emoji: '👐', name: 'open_hands', keywords: ['jazz_hands'] },
      { emoji: '🤲', name: 'palms_up', keywords: ['prayer'] },
      { emoji: '🤝', name: 'handshake', keywords: ['deal', 'agreement'] },
      { emoji: '🙏', name: 'pray', keywords: ['please', 'thanks', 'namaste'] },
      { emoji: '✍️', name: 'writing', keywords: ['write'] },
      { emoji: '💅', name: 'nail_polish', keywords: ['beauty', 'sassy'] },
      { emoji: '🤳', name: 'selfie', keywords: ['photo'] },
      { emoji: '💪', name: 'muscle', keywords: ['strong', 'bicep', 'flex'] },
      { emoji: '🦵', name: 'leg', keywords: ['kick'] },
      { emoji: '🦶', name: 'foot', keywords: ['kick'] },
      { emoji: '👂', name: 'ear', keywords: ['listen', 'hear'] },
      { emoji: '👃', name: 'nose', keywords: ['smell'] },
      { emoji: '🧠', name: 'brain', keywords: ['smart', 'think'] },
      { emoji: '👀', name: 'eyes', keywords: ['look', 'see', 'watch'] },
      { emoji: '👁️', name: 'eye', keywords: ['look'] },
      { emoji: '👅', name: 'tongue', keywords: ['taste'] },
      { emoji: '👄', name: 'lips', keywords: ['kiss', 'mouth'] },
      { emoji: '🫦', name: 'biting_lip', keywords: ['nervous', 'flirt'] },
      { emoji: '👶', name: 'baby', keywords: ['child', 'infant'] },
      { emoji: '🧒', name: 'child', keywords: ['kid'] },
      { emoji: '👦', name: 'boy', keywords: ['male', 'kid'] },
      { emoji: '👧', name: 'girl', keywords: ['female', 'kid'] },
      { emoji: '🧑', name: 'person', keywords: ['adult'] },
      { emoji: '👨', name: 'man', keywords: ['male', 'adult'] },
      { emoji: '👩', name: 'woman', keywords: ['female', 'adult'] },
      { emoji: '🧓', name: 'older_person', keywords: ['elderly'] },
      { emoji: '👴', name: 'old_man', keywords: ['elderly', 'grandfather'] },
      { emoji: '👵', name: 'old_woman', keywords: ['elderly', 'grandmother'] },
    ],
  },
  {
    id: 'nature',
    icon: '🐶',
    emojis: [
      { emoji: '🐶', name: 'dog', keywords: ['puppy', 'pet'] },
      { emoji: '🐱', name: 'cat', keywords: ['kitten', 'pet'] },
      { emoji: '🐭', name: 'mouse', keywords: ['rodent'] },
      { emoji: '🐹', name: 'hamster', keywords: ['pet'] },
      { emoji: '🐰', name: 'rabbit', keywords: ['bunny'] },
      { emoji: '🦊', name: 'fox', keywords: ['cunning'] },
      { emoji: '🐻', name: 'bear', keywords: ['teddy'] },
      { emoji: '🐼', name: 'panda', keywords: ['bear'] },
      { emoji: '🐨', name: 'koala', keywords: ['bear'] },
      { emoji: '🐯', name: 'tiger', keywords: ['cat'] },
      { emoji: '🦁', name: 'lion', keywords: ['king'] },
      { emoji: '🐮', name: 'cow', keywords: ['moo'] },
      { emoji: '🐷', name: 'pig', keywords: ['oink'] },
      { emoji: '🐸', name: 'frog', keywords: ['toad'] },
      { emoji: '🐵', name: 'monkey', keywords: ['ape'] },
      { emoji: '🙈', name: 'see_no_evil', keywords: ['monkey', 'shy'] },
      { emoji: '🙉', name: 'hear_no_evil', keywords: ['monkey'] },
      { emoji: '🙊', name: 'speak_no_evil', keywords: ['monkey'] },
      { emoji: '🐔', name: 'chicken', keywords: ['bird'] },
      { emoji: '🐧', name: 'penguin', keywords: ['bird'] },
      { emoji: '🐦', name: 'bird', keywords: ['tweet'] },
      { emoji: '🦆', name: 'duck', keywords: ['bird'] },
      { emoji: '🦅', name: 'eagle', keywords: ['bird'] },
      { emoji: '🦉', name: 'owl', keywords: ['wise'] },
      { emoji: '🦇', name: 'bat', keywords: ['vampire'] },
      { emoji: '🐺', name: 'wolf', keywords: ['howl'] },
      { emoji: '🐗', name: 'boar', keywords: ['pig'] },
      { emoji: '🐴', name: 'horse', keywords: ['pony'] },
      { emoji: '🦄', name: 'unicorn', keywords: ['magical', 'fantasy'] },
      { emoji: '🐝', name: 'bee', keywords: ['honey'] },
      { emoji: '🪱', name: 'worm', keywords: ['bug'] },
      { emoji: '🐛', name: 'bug', keywords: ['insect'] },
      { emoji: '🦋', name: 'butterfly', keywords: ['insect', 'pretty'] },
      { emoji: '🐌', name: 'snail', keywords: ['slow'] },
      { emoji: '🐞', name: 'ladybug', keywords: ['bug'] },
      { emoji: '🐜', name: 'ant', keywords: ['insect'] },
      { emoji: '🪰', name: 'fly', keywords: ['insect'] },
      { emoji: '🐢', name: 'turtle', keywords: ['slow'] },
      { emoji: '🐍', name: 'snake', keywords: ['reptile'] },
      { emoji: '🦎', name: 'lizard', keywords: ['reptile'] },
      { emoji: '🦂', name: 'scorpion', keywords: ['arachnid'] },
      { emoji: '🐙', name: 'octopus', keywords: ['ocean'] },
      { emoji: '🦑', name: 'squid', keywords: ['ocean'] },
      { emoji: '🦐', name: 'shrimp', keywords: ['seafood'] },
      { emoji: '🦀', name: 'crab', keywords: ['seafood'] },
      { emoji: '🐡', name: 'blowfish', keywords: ['fish'] },
      { emoji: '🐠', name: 'tropical_fish', keywords: ['fish'] },
      { emoji: '🐟', name: 'fish', keywords: ['seafood'] },
      { emoji: '🐬', name: 'dolphin', keywords: ['ocean'] },
      { emoji: '🐳', name: 'whale', keywords: ['ocean'] },
      { emoji: '🦈', name: 'shark', keywords: ['ocean', 'danger'] },
      { emoji: '🐊', name: 'crocodile', keywords: ['reptile'] },
      { emoji: '🐘', name: 'elephant', keywords: ['big'] },
      { emoji: '🦛', name: 'hippo', keywords: ['animal'] },
      { emoji: '🦏', name: 'rhino', keywords: ['animal'] },
      { emoji: '🐪', name: 'camel', keywords: ['desert'] },
      { emoji: '🦒', name: 'giraffe', keywords: ['tall'] },
      { emoji: '🦘', name: 'kangaroo', keywords: ['australia'] },
      { emoji: '🐾', name: 'paw_prints', keywords: ['animal', 'pet'] },
      { emoji: '🌸', name: 'cherry_blossom', keywords: ['flower', 'spring'] },
      { emoji: '💐', name: 'bouquet', keywords: ['flowers'] },
      { emoji: '🌹', name: 'rose', keywords: ['flower', 'love'] },
      { emoji: '🌺', name: 'hibiscus', keywords: ['flower'] },
      { emoji: '🌻', name: 'sunflower', keywords: ['flower'] },
      { emoji: '🌷', name: 'tulip', keywords: ['flower'] },
      { emoji: '🌱', name: 'seedling', keywords: ['plant', 'grow'] },
      { emoji: '🪴', name: 'potted_plant', keywords: ['plant'] },
      { emoji: '🌲', name: 'evergreen', keywords: ['tree'] },
      { emoji: '🌳', name: 'deciduous_tree', keywords: ['tree'] },
      { emoji: '🌴', name: 'palm_tree', keywords: ['beach', 'tropical'] },
      { emoji: '🌵', name: 'cactus', keywords: ['desert', 'plant'] },
      { emoji: '🍀', name: 'four_leaf_clover', keywords: ['lucky', 'luck'] },
      { emoji: '🍁', name: 'maple_leaf', keywords: ['fall', 'autumn'] },
      { emoji: '🍂', name: 'fallen_leaf', keywords: ['autumn'] },
      { emoji: '🍃', name: 'leaves', keywords: ['wind'] },
    ],
  },
  {
    id: 'food',
    icon: '🍔',
    emojis: [
      { emoji: '🍎', name: 'apple', keywords: ['fruit'] },
      { emoji: '🍊', name: 'orange', keywords: ['fruit'] },
      { emoji: '🍋', name: 'lemon', keywords: ['fruit', 'sour'] },
      { emoji: '🍌', name: 'banana', keywords: ['fruit'] },
      { emoji: '🍉', name: 'watermelon', keywords: ['fruit'] },
      { emoji: '🍇', name: 'grapes', keywords: ['fruit'] },
      { emoji: '🍓', name: 'strawberry', keywords: ['fruit'] },
      { emoji: '🫐', name: 'blueberries', keywords: ['fruit'] },
      { emoji: '🍈', name: 'melon', keywords: ['fruit'] },
      { emoji: '🍒', name: 'cherries', keywords: ['fruit'] },
      { emoji: '🍑', name: 'peach', keywords: ['fruit'] },
      { emoji: '🥭', name: 'mango', keywords: ['fruit'] },
      { emoji: '🍍', name: 'pineapple', keywords: ['fruit'] },
      { emoji: '🥥', name: 'coconut', keywords: ['fruit'] },
      { emoji: '🥝', name: 'kiwi', keywords: ['fruit'] },
      { emoji: '🍅', name: 'tomato', keywords: ['vegetable'] },
      { emoji: '🥑', name: 'avocado', keywords: ['fruit'] },
      { emoji: '🥦', name: 'broccoli', keywords: ['vegetable'] },
      { emoji: '🥬', name: 'leafy_green', keywords: ['vegetable'] },
      { emoji: '🥒', name: 'cucumber', keywords: ['vegetable'] },
      { emoji: '🌶️', name: 'hot_pepper', keywords: ['spicy'] },
      { emoji: '🫑', name: 'bell_pepper', keywords: ['vegetable'] },
      { emoji: '🌽', name: 'corn', keywords: ['vegetable'] },
      { emoji: '🥕', name: 'carrot', keywords: ['vegetable'] },
      { emoji: '🧄', name: 'garlic', keywords: ['vegetable'] },
      { emoji: '🧅', name: 'onion', keywords: ['vegetable'] },
      { emoji: '🥔', name: 'potato', keywords: ['vegetable'] },
      { emoji: '🍞', name: 'bread', keywords: ['food'] },
      { emoji: '🥐', name: 'croissant', keywords: ['bread', 'french'] },
      { emoji: '🥖', name: 'baguette', keywords: ['bread', 'french'] },
      { emoji: '🧀', name: 'cheese', keywords: ['food'] },
      { emoji: '🥚', name: 'egg', keywords: ['food'] },
      { emoji: '🍳', name: 'cooking', keywords: ['egg', 'breakfast'] },
      { emoji: '🥞', name: 'pancakes', keywords: ['breakfast'] },
      { emoji: '🧇', name: 'waffle', keywords: ['breakfast'] },
      { emoji: '🥓', name: 'bacon', keywords: ['meat', 'breakfast'] },
      { emoji: '🍔', name: 'hamburger', keywords: ['burger', 'fast_food'] },
      { emoji: '🍟', name: 'fries', keywords: ['fast_food'] },
      { emoji: '🍕', name: 'pizza', keywords: ['food'] },
      { emoji: '🌭', name: 'hot_dog', keywords: ['food'] },
      { emoji: '🥪', name: 'sandwich', keywords: ['food'] },
      { emoji: '🌮', name: 'taco', keywords: ['mexican'] },
      { emoji: '🌯', name: 'burrito', keywords: ['mexican'] },
      { emoji: '🥗', name: 'salad', keywords: ['healthy'] },
      { emoji: '🍝', name: 'spaghetti', keywords: ['pasta', 'italian'] },
      { emoji: '🍜', name: 'ramen', keywords: ['noodles', 'japanese'] },
      { emoji: '🍲', name: 'stew', keywords: ['food', 'soup'] },
      { emoji: '🍛', name: 'curry', keywords: ['indian', 'food'] },
      { emoji: '🍣', name: 'sushi', keywords: ['japanese'] },
      { emoji: '🍱', name: 'bento', keywords: ['japanese', 'lunch'] },
      { emoji: '🍤', name: 'fried_shrimp', keywords: ['tempura'] },
      { emoji: '🍙', name: 'rice_ball', keywords: ['japanese'] },
      { emoji: '🍚', name: 'rice', keywords: ['food'] },
      { emoji: '🍰', name: 'cake', keywords: ['dessert'] },
      { emoji: '🎂', name: 'birthday_cake', keywords: ['birthday', 'celebration'] },
      { emoji: '🧁', name: 'cupcake', keywords: ['dessert'] },
      { emoji: '🍩', name: 'doughnut', keywords: ['dessert'] },
      { emoji: '🍪', name: 'cookie', keywords: ['dessert'] },
      { emoji: '🍫', name: 'chocolate', keywords: ['candy'] },
      { emoji: '🍬', name: 'candy', keywords: ['sweet'] },
      { emoji: '🍭', name: 'lollipop', keywords: ['candy'] },
      { emoji: '🍦', name: 'ice_cream', keywords: ['dessert'] },
      { emoji: '☕', name: 'coffee', keywords: ['drink', 'cafe'] },
      { emoji: '🍵', name: 'tea', keywords: ['drink'] },
      { emoji: '🧃', name: 'juice_box', keywords: ['drink'] },
      { emoji: '🥤', name: 'cup_with_straw', keywords: ['drink'] },
      { emoji: '🧋', name: 'bubble_tea', keywords: ['boba', 'drink'] },
      { emoji: '🍺', name: 'beer', keywords: ['drink', 'alcohol'] },
      { emoji: '🍻', name: 'beers', keywords: ['cheers', 'drink'] },
      { emoji: '🥂', name: 'champagne_glasses', keywords: ['cheers', 'toast'] },
      { emoji: '🍷', name: 'wine', keywords: ['drink', 'alcohol'] },
      { emoji: '🍸', name: 'cocktail', keywords: ['drink'] },
      { emoji: '🧊', name: 'ice', keywords: ['cold'] },
    ],
  },
  {
    id: 'activities',
    icon: '⚽',
    emojis: [
      { emoji: '⚽', name: 'soccer', keywords: ['football', 'sport'] },
      { emoji: '🏀', name: 'basketball', keywords: ['sport'] },
      { emoji: '🏈', name: 'football', keywords: ['sport', 'american'] },
      { emoji: '⚾', name: 'baseball', keywords: ['sport'] },
      { emoji: '🥎', name: 'softball', keywords: ['sport'] },
      { emoji: '🎾', name: 'tennis', keywords: ['sport'] },
      { emoji: '🏐', name: 'volleyball', keywords: ['sport'] },
      { emoji: '🏉', name: 'rugby', keywords: ['sport'] },
      { emoji: '🥏', name: 'frisbee', keywords: ['sport'] },
      { emoji: '🎱', name: 'pool', keywords: ['billiards'] },
      { emoji: '🏓', name: 'ping_pong', keywords: ['table_tennis'] },
      { emoji: '🏸', name: 'badminton', keywords: ['sport'] },
      { emoji: '🏒', name: 'ice_hockey', keywords: ['sport'] },
      { emoji: '🥅', name: 'goal', keywords: ['sport'] },
      { emoji: '⛳', name: 'golf', keywords: ['sport'] },
      { emoji: '🏹', name: 'archery', keywords: ['bow'] },
      { emoji: '🎣', name: 'fishing', keywords: ['fish'] },
      { emoji: '🥊', name: 'boxing', keywords: ['sport', 'fight'] },
      { emoji: '🥋', name: 'martial_arts', keywords: ['karate', 'judo'] },
      { emoji: '🎿', name: 'ski', keywords: ['winter', 'sport'] },
      { emoji: '⛷️', name: 'skier', keywords: ['sport'] },
      { emoji: '🏂', name: 'snowboard', keywords: ['winter', 'sport'] },
      { emoji: '🏋️', name: 'weight_lifting', keywords: ['gym'] },
      { emoji: '🤼', name: 'wrestling', keywords: ['sport'] },
      { emoji: '🤸', name: 'gymnastics', keywords: ['sport'] },
      { emoji: '🏊', name: 'swimming', keywords: ['sport', 'water'] },
      { emoji: '🚴', name: 'cycling', keywords: ['bike', 'sport'] },
      { emoji: '🧘', name: 'yoga', keywords: ['meditation'] },
      { emoji: '🎮', name: 'video_game', keywords: ['gaming', 'controller'] },
      { emoji: '🕹️', name: 'joystick', keywords: ['gaming'] },
      { emoji: '🎲', name: 'dice', keywords: ['game', 'random'] },
      { emoji: '🧩', name: 'puzzle', keywords: ['game'] },
      { emoji: '♟️', name: 'chess', keywords: ['game', 'strategy'] },
      { emoji: '🎯', name: 'bullseye', keywords: ['target', 'goal'] },
      { emoji: '🎳', name: 'bowling', keywords: ['sport'] },
      { emoji: '🎭', name: 'performing_arts', keywords: ['theater', 'drama'] },
      { emoji: '🎨', name: 'palette', keywords: ['art', 'paint'] },
      { emoji: '🎬', name: 'clapper', keywords: ['movie', 'film'] },
      { emoji: '🎤', name: 'microphone', keywords: ['sing', 'music'] },
      { emoji: '🎧', name: 'headphones', keywords: ['music'] },
      { emoji: '🎼', name: 'musical_score', keywords: ['music'] },
      { emoji: '🎹', name: 'piano', keywords: ['music'] },
      { emoji: '🥁', name: 'drum', keywords: ['music'] },
      { emoji: '🎷', name: 'saxophone', keywords: ['music', 'jazz'] },
      { emoji: '🎺', name: 'trumpet', keywords: ['music'] },
      { emoji: '🎸', name: 'guitar', keywords: ['music', 'rock'] },
      { emoji: '🎻', name: 'violin', keywords: ['music'] },
      { emoji: '🎪', name: 'circus', keywords: ['entertainment'] },
      { emoji: '🎟️', name: 'ticket', keywords: ['event'] },
      { emoji: '🏆', name: 'trophy', keywords: ['win', 'award'] },
      { emoji: '🥇', name: 'gold_medal', keywords: ['first', 'win'] },
      { emoji: '🥈', name: 'silver_medal', keywords: ['second'] },
      { emoji: '🥉', name: 'bronze_medal', keywords: ['third'] },
      { emoji: '🏅', name: 'medal', keywords: ['award'] },
    ],
  },
  {
    id: 'travel',
    icon: '🚗',
    emojis: [
      { emoji: '🚗', name: 'car', keywords: ['vehicle', 'drive'] },
      { emoji: '🚕', name: 'taxi', keywords: ['cab'] },
      { emoji: '🚌', name: 'bus', keywords: ['transport'] },
      { emoji: '🚎', name: 'trolleybus', keywords: ['transport'] },
      { emoji: '🏎️', name: 'race_car', keywords: ['fast'] },
      { emoji: '🚓', name: 'police_car', keywords: ['law'] },
      { emoji: '🚑', name: 'ambulance', keywords: ['medical'] },
      { emoji: '🚒', name: 'fire_engine', keywords: ['emergency'] },
      { emoji: '🚐', name: 'minibus', keywords: ['van'] },
      { emoji: '🛻', name: 'pickup_truck', keywords: ['vehicle'] },
      { emoji: '🚚', name: 'truck', keywords: ['delivery'] },
      { emoji: '🚂', name: 'locomotive', keywords: ['train'] },
      { emoji: '🚆', name: 'train', keywords: ['transport'] },
      { emoji: '✈️', name: 'airplane', keywords: ['travel', 'fly'] },
      { emoji: '🚀', name: 'rocket', keywords: ['space', 'launch'] },
      { emoji: '🛸', name: 'ufo', keywords: ['alien'] },
      { emoji: '🚁', name: 'helicopter', keywords: ['fly'] },
      { emoji: '⛵', name: 'sailboat', keywords: ['boat'] },
      { emoji: '🚢', name: 'ship', keywords: ['boat'] },
      { emoji: '🏠', name: 'house', keywords: ['home'] },
      { emoji: '🏡', name: 'house_garden', keywords: ['home'] },
      { emoji: '🏢', name: 'office', keywords: ['building'] },
      { emoji: '🏥', name: 'hospital', keywords: ['medical'] },
      { emoji: '🏫', name: 'school', keywords: ['education'] },
      { emoji: '🏪', name: 'store', keywords: ['shop'] },
      { emoji: '🏰', name: 'castle', keywords: ['building'] },
      { emoji: '🗽', name: 'statue_liberty', keywords: ['new_york'] },
      { emoji: '🗼', name: 'tokyo_tower', keywords: ['japan'] },
      { emoji: '🌍', name: 'earth_africa', keywords: ['world', 'globe'] },
      { emoji: '🌎', name: 'earth_americas', keywords: ['world', 'globe'] },
      { emoji: '🌏', name: 'earth_asia', keywords: ['world', 'globe'] },
      { emoji: '🌙', name: 'crescent_moon', keywords: ['night'] },
      { emoji: '🌛', name: 'first_quarter_moon_face', keywords: ['moon'] },
      { emoji: '⭐', name: 'star', keywords: ['favorite'] },
      { emoji: '🌟', name: 'glowing_star', keywords: ['sparkle'] },
      { emoji: '✨', name: 'sparkles', keywords: ['magic', 'shiny'] },
      { emoji: '⚡', name: 'zap', keywords: ['lightning', 'electricity'] },
      { emoji: '🔥', name: 'fire', keywords: ['hot', 'flame', 'lit'] },
      { emoji: '🌈', name: 'rainbow', keywords: ['color'] },
      { emoji: '☀️', name: 'sun', keywords: ['sunny', 'bright'] },
      { emoji: '🌤️', name: 'partly_sunny', keywords: ['weather'] },
      { emoji: '⛅', name: 'cloudy', keywords: ['weather'] },
      { emoji: '🌧️', name: 'rain', keywords: ['weather'] },
      { emoji: '❄️', name: 'snowflake', keywords: ['cold', 'winter'] },
      { emoji: '🌊', name: 'wave', keywords: ['ocean', 'water'] },
    ],
  },
  {
    id: 'objects',
    icon: '💡',
    emojis: [
      { emoji: '⌚', name: 'watch', keywords: ['time'] },
      { emoji: '📱', name: 'phone', keywords: ['mobile', 'cell'] },
      { emoji: '💻', name: 'laptop', keywords: ['computer'] },
      { emoji: '⌨️', name: 'keyboard', keywords: ['computer'] },
      { emoji: '🖥️', name: 'desktop', keywords: ['computer'] },
      { emoji: '🖨️', name: 'printer', keywords: ['computer'] },
      { emoji: '🖱️', name: 'mouse', keywords: ['computer'] },
      { emoji: '💾', name: 'floppy_disk', keywords: ['save'] },
      { emoji: '💿', name: 'cd', keywords: ['disc'] },
      { emoji: '📷', name: 'camera', keywords: ['photo'] },
      { emoji: '🎥', name: 'movie_camera', keywords: ['film', 'video'] },
      { emoji: '📺', name: 'tv', keywords: ['television'] },
      { emoji: '📻', name: 'radio', keywords: ['music'] },
      { emoji: '🔔', name: 'bell', keywords: ['notification'] },
      { emoji: '🔕', name: 'no_bell', keywords: ['mute'] },
      { emoji: '📣', name: 'megaphone', keywords: ['loud'] },
      { emoji: '💡', name: 'bulb', keywords: ['idea', 'light'] },
      { emoji: '🔦', name: 'flashlight', keywords: ['light'] },
      { emoji: '🕯️', name: 'candle', keywords: ['light'] },
      { emoji: '📖', name: 'book', keywords: ['read'] },
      { emoji: '📚', name: 'books', keywords: ['read', 'library'] },
      { emoji: '📝', name: 'memo', keywords: ['write', 'note'] },
      { emoji: '✏️', name: 'pencil', keywords: ['write'] },
      { emoji: '🖊️', name: 'pen', keywords: ['write'] },
      { emoji: '📌', name: 'pin', keywords: ['location'] },
      { emoji: '📎', name: 'paperclip', keywords: ['attach'] },
      { emoji: '🔗', name: 'link', keywords: ['url', 'chain'] },
      { emoji: '📊', name: 'bar_chart', keywords: ['graph', 'stats'] },
      { emoji: '📈', name: 'chart_up', keywords: ['graph', 'increase'] },
      { emoji: '📉', name: 'chart_down', keywords: ['graph', 'decrease'] },
      { emoji: '🗂️', name: 'card_index', keywords: ['file', 'organize'] },
      { emoji: '📁', name: 'folder', keywords: ['file'] },
      { emoji: '📂', name: 'open_folder', keywords: ['file'] },
      { emoji: '🗑️', name: 'wastebasket', keywords: ['trash', 'delete'] },
      { emoji: '🔒', name: 'lock', keywords: ['security'] },
      { emoji: '🔓', name: 'unlock', keywords: ['security'] },
      { emoji: '🔑', name: 'key', keywords: ['password'] },
      { emoji: '🔧', name: 'wrench', keywords: ['tool'] },
      { emoji: '🔨', name: 'hammer', keywords: ['tool'] },
      { emoji: '⚙️', name: 'gear', keywords: ['settings'] },
      { emoji: '🧲', name: 'magnet', keywords: ['attract'] },
      { emoji: '💎', name: 'gem', keywords: ['diamond', 'jewel'] },
      { emoji: '🧸', name: 'teddy_bear', keywords: ['toy', 'stuffed'] },
      { emoji: '🎁', name: 'gift', keywords: ['present', 'birthday'] },
      { emoji: '🎀', name: 'ribbon', keywords: ['bow'] },
      { emoji: '🎈', name: 'balloon', keywords: ['party'] },
      { emoji: '🎉', name: 'tada', keywords: ['party', 'celebrate', 'congratulations'] },
      { emoji: '🎊', name: 'confetti', keywords: ['party', 'celebrate'] },
      { emoji: '🎃', name: 'jack_o_lantern', keywords: ['halloween'] },
      { emoji: '🎄', name: 'christmas_tree', keywords: ['holiday'] },
      { emoji: '🎆', name: 'fireworks', keywords: ['celebrate'] },
      { emoji: '🎇', name: 'sparkler', keywords: ['celebrate'] },
      { emoji: '💌', name: 'love_letter', keywords: ['email', 'heart'] },
      { emoji: '📧', name: 'email', keywords: ['mail'] },
      { emoji: '📦', name: 'package', keywords: ['box', 'delivery'] },
    ],
  },
  {
    id: 'symbols',
    icon: '❤️',
    emojis: [
      { emoji: '❤️', name: 'red_heart', keywords: ['love'] },
      { emoji: '🧡', name: 'orange_heart', keywords: ['love'] },
      { emoji: '💛', name: 'yellow_heart', keywords: ['love'] },
      { emoji: '💚', name: 'green_heart', keywords: ['love'] },
      { emoji: '💙', name: 'blue_heart', keywords: ['love'] },
      { emoji: '💜', name: 'purple_heart', keywords: ['love'] },
      { emoji: '🖤', name: 'black_heart', keywords: ['love'] },
      { emoji: '🤍', name: 'white_heart', keywords: ['love'] },
      { emoji: '🤎', name: 'brown_heart', keywords: ['love'] },
      { emoji: '💔', name: 'broken_heart', keywords: ['sad'] },
      { emoji: '❤️‍🔥', name: 'heart_fire', keywords: ['love', 'passion'] },
      { emoji: '❤️‍🩹', name: 'mending_heart', keywords: ['heal'] },
      { emoji: '💕', name: 'two_hearts', keywords: ['love'] },
      { emoji: '💞', name: 'revolving_hearts', keywords: ['love'] },
      { emoji: '💓', name: 'heartbeat', keywords: ['love'] },
      { emoji: '💗', name: 'growing_heart', keywords: ['love'] },
      { emoji: '💖', name: 'sparkling_heart', keywords: ['love'] },
      { emoji: '💘', name: 'cupid', keywords: ['love', 'arrow'] },
      { emoji: '💝', name: 'gift_heart', keywords: ['love'] },
      { emoji: '💟', name: 'heart_decoration', keywords: ['love'] },
      { emoji: '💯', name: 'hundred', keywords: ['perfect', 'score'] },
      { emoji: '💢', name: 'anger', keywords: ['mad'] },
      { emoji: '💥', name: 'boom', keywords: ['explosion'] },
      { emoji: '💫', name: 'dizzy', keywords: ['star'] },
      { emoji: '💦', name: 'sweat_drops', keywords: ['water'] },
      { emoji: '💨', name: 'dash', keywords: ['wind', 'fast'] },
      { emoji: '🕳️', name: 'hole', keywords: ['void'] },
      { emoji: '💬', name: 'speech_bubble', keywords: ['comment', 'chat'] },
      { emoji: '💭', name: 'thought_bubble', keywords: ['think'] },
      { emoji: '🗯️', name: 'anger_bubble', keywords: ['mad'] },
      { emoji: '❗', name: 'exclamation', keywords: ['important', 'bang'] },
      { emoji: '❓', name: 'question', keywords: ['what', 'confused'] },
      { emoji: '‼️', name: 'double_exclamation', keywords: ['important'] },
      { emoji: '⁉️', name: 'exclamation_question', keywords: ['surprise'] },
      { emoji: '✅', name: 'check', keywords: ['yes', 'done', 'correct'] },
      { emoji: '❌', name: 'cross', keywords: ['no', 'wrong', 'delete'] },
      { emoji: '⭕', name: 'circle', keywords: ['round'] },
      { emoji: '🚫', name: 'no_entry', keywords: ['forbidden', 'stop'] },
      { emoji: '♻️', name: 'recycle', keywords: ['environment'] },
      { emoji: '✳️', name: 'eight_pointed_star', keywords: ['star'] },
      { emoji: '🔴', name: 'red_circle', keywords: ['dot'] },
      { emoji: '🟠', name: 'orange_circle', keywords: ['dot'] },
      { emoji: '🟡', name: 'yellow_circle', keywords: ['dot'] },
      { emoji: '🟢', name: 'green_circle', keywords: ['dot'] },
      { emoji: '🔵', name: 'blue_circle', keywords: ['dot'] },
      { emoji: '🟣', name: 'purple_circle', keywords: ['dot'] },
      { emoji: '🔶', name: 'large_orange_diamond', keywords: ['shape'] },
      { emoji: '🔷', name: 'large_blue_diamond', keywords: ['shape'] },
      { emoji: '▶️', name: 'play', keywords: ['start'] },
      { emoji: '⏸️', name: 'pause', keywords: ['stop'] },
      { emoji: '⏹️', name: 'stop_button', keywords: ['stop'] },
      { emoji: '⏩', name: 'fast_forward', keywords: ['skip'] },
      { emoji: '⏪', name: 'rewind', keywords: ['back'] },
      { emoji: '🔀', name: 'shuffle', keywords: ['random'] },
      { emoji: '🔁', name: 'repeat', keywords: ['loop'] },
      { emoji: '🔂', name: 'repeat_one', keywords: ['loop'] },
      { emoji: '➕', name: 'plus', keywords: ['add'] },
      { emoji: '➖', name: 'minus', keywords: ['subtract'] },
      { emoji: '➗', name: 'divide', keywords: ['math'] },
      { emoji: '✖️', name: 'multiply', keywords: ['math'] },
      { emoji: '♾️', name: 'infinity', keywords: ['forever'] },
      { emoji: '💲', name: 'dollar', keywords: ['money'] },
      { emoji: '©️', name: 'copyright', keywords: ['legal'] },
      { emoji: '®️', name: 'registered', keywords: ['legal'] },
      { emoji: '™️', name: 'trademark', keywords: ['legal'] },
      { emoji: '🏳️', name: 'white_flag', keywords: ['surrender'] },
      { emoji: '🏴', name: 'black_flag', keywords: ['pirate'] },
      { emoji: '🚩', name: 'red_flag', keywords: ['warning', 'triangular_flag'] },
      { emoji: '🏁', name: 'checkered_flag', keywords: ['finish', 'race'] },
    ],
  },
]

// Flat list for search
let _allEmojis: EmojiItem[] | null = null

export function getAllEmojis(): EmojiItem[] {
  if (!_allEmojis) {
    _allEmojis = EMOJI_CATEGORIES.flatMap(cat => cat.emojis)
  }
  return _allEmojis
}

export function searchEmojis(query: string, limit = 50): EmojiItem[] {
  if (!query.trim()) return []
  const q = query.toLowerCase().trim()
  const results: EmojiItem[] = []

  for (const emoji of getAllEmojis()) {
    if (results.length >= limit) break
    if (
      emoji.name.includes(q)
      || emoji.keywords.some(k => k.includes(q))
      || emoji.emoji === q
    ) {
      results.push(emoji)
    }
  }

  return results
}

export const QUICK_REACTIONS = ['👍', '❤️', '😂', '😮', '😢', '🎉']
